version: "3.1"
services:
  web:
    build:
        context: nuxt-firebase-docker
        dockerfile: Dockerfile
    container_name: nuxt-firebase-docker
    command: sh /init.sh
    volumes:
      - ./app:/code
    ports:
      - "3000:3000"
      - "8888:8888"
